# Generated by Django 5.1 on 2024-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='user',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
