# Generated by Django 5.1 on 2024-10-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('update_message', models.TextField()),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.transportationprovider')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.CharField(max_length=255)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.transportationprovider')),
            ],
        ),
        migrations.CreateModel(
            name='RideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('ride_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.BooleanField(default=False)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.transportationprovider')),
            ],
        ),
    ]
